### ISSUE TITLE
Disable "Delete all points" button

### ISSUE THREAD

**Issue by macrintr** [seung-lab/neuroglancer#10]
![selection_512](https://cloud.githubusercontent.com/assets/4612954/23575005/0d8756e6-0054-11e7-9b36-77d111acf6f9.jpg)

**Comment by nkemnitz** [comment]
@macrintr: Still an issue?

**Comment by nkemnitz** [comment]
Resolved with the new annotation tools in 9c8a392391452b55b99ce597a7e5b94bef5620a3
