### ISSUE TITLE
Task composability

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#102]
Task composition, reduce IO operations by composing tasks which depends on same data. for example, run chunk watershed.

Can we think of a way of specifying task so that we can merge inference with watershed such that the affinities are not uploaded to be later download for the watershed task?
Is this a good pattern or should we just manually create a new task that does this?

**Comment by william-silversmith** [comment]
No where near complete for this issue, but CloudVolume now supports the `cache=True` flag. If dependent tasks run on the same machine, they can reuse the data on disk (which could even be a ram disk).

**Comment by nkemnitz** [comment]
Now handled in [Igneous](https://github.com/seung-lab/igneous)
