### ISSUE TITLE
Mesh Compression

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#105]
We need to first understand where time is being spent when displaying meshing.
After that, If downloading it's a major part of it, using some form of meshing compression should help
https://github.com/google/draco

**Comment by william-silversmith** [comment]
I sent an email to the Draco team asking for any publications and other
tool comparisons. I'm waiting to hear back. They only published a
comparison to gzip which is an easy target.

**Comment by william-silversmith** [comment]
Here's one comparison someone did: https://developer.box.com/v2.0/blog/showdown-3d-model-compression-at-scale-draco-vs-open3dgc

Here's Google's vs gzip comparison: https://opensource.googleblog.com/2017/01/introducing-draco-compression-for-3d.html

**Comment by nkemnitz** [comment]
Draco support has been added in #247. Should create a PR for Google.

**Comment by nkemnitz** [comment]
Moving discussion to PR https://github.com/google/neuroglancer/pull/131
