### ISSUE TITLE
State Server

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#106]
Improve synchronization between frontend and server.
Add a way of specifying the port the state server is running in example.py and document it.
Add a way of programmatically adding new shortcuts which events are handled by the state server.

The state server was developed in only a few hours, and it had provided everyone in the lab with the ability to design a tool that suite their needs. Time invested here will make them even more productive.

**Comment by nkemnitz** [comment]
Using jbms's state server - Tommy seems happy
