### ISSUE TITLE
 Lines not shown on Mac OS

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#107]
For some reason lines between synapses points are not being displayed.

**Comment by nkemnitz** [comment]
Considering that glLineWidth() is also limited to a useless 1.0 on Windows machines, we should probably replace GL_LINES with a thin triangle strip and avoid all those line related problems.

**Comment by nkemnitz** [comment]
Solved in ad570914d713357761ff71b7bd676e0ccea5a254
