### ISSUE TITLE
Semantic Segmentation state

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#108]
When doing semantic annotation in the segmentation layer, the state is not visible in the global state passed to the state server, making impossible for a user to save the changes.

For a large datasets and multiple users annotation we will probably want something else than a state server scripts, possibly a technology related to how graph operations are saved #97

**Comment by tartavull** [comment]
Should be similar to what happening with equivalances
https://github.com/seung-lab/neuroglancer/blob/master/src/neuroglancer/segmentation_user_layer.ts#L186

**Comment by tartavull** [comment]
Should we extend equivalences to have multiple values instead of just one?

**Comment by nkemnitz** [comment]
Outdated, abandoned. Future Nico will maybe deal with semantic labels.
