### ISSUE TITLE
Performance Meshing

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#111]
Experiment with running meshing on down-sample segmentations.
Specially useful when doing human intervention to show meshes faster to the users.

**Comment by william-silversmith** [comment]
This is already done.

**Comment by william-silversmith** [comment]
https://github.com/seung-lab/neuroglancer/pull/159

**Comment by jingpengw** [comment]
it was fixed. close here?

**Comment by jingpengw** [comment]
oh, it was not merged yet.
