### ISSUE TITLE
Eyewire database to relabel

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#115]
Read the eyewire database to create a relabel task to be able to see complete neurons of e2198 and zebrafish on neuroglancer.

**Comment by william-silversmith** [comment]
We need to remap e2198 based on physical space first. Right now it's in uint16s (like in Eyewire) which means the same segids repeat all over the dataset.

**Comment by tartavull** [comment]
We probably want to use our workstation to query the database and create a mapping for every eyewire cube from cell id to list of supervoxels ids.
We can then upload every one of this mapping to cloud storage. We want to do it this way so that task don't need to have access to the eyewire database.

Then a relabeling task that fetches the chunk , fetches the corresponding mapping file and applies it and finally saves to a segmentation with enough bits to accommodate all cells. 
It also has to make sure that cell ids don't collide with supervoxels ids, a possible way is by converting into a 32 bit segmentation, and use the upper 16 bit for cell ids.

Eyewire overlapping causes inconsistencies which would take hacks/time to make a better mapping, we should do the easiest thing first and see if it is worth trying to develop this hacks.

**Comment by tartavull** [comment]
RelabelTask definition which has to be modified
https://github.com/seung-lab/neuroglancer/blob/cleanup_yacn/python/neuroglancer/pipeline/task_yacn.py#L425

**Comment by tartavull** [comment]
Test for relabeling task
https://github.com/seung-lab/neuroglancer/blob/cleanup_yacn/python/test/test_tasks.py#L120

**Comment by william-silversmith** [comment]
There's a HyperSquareConsensusTask in here: https://github.com/seung-lab/neuroglancer/pull/159
