### ISSUE TITLE
Synapse editor

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#116]
Current Neuroscience efforts requires a way to save to persistent storage the modifications introduce by user when doing synapse editing.

**Comment by nkemnitz** [comment]
@macrintr @nicholasturner1 Do you have any input on this? Still required or does your state server handle everything you need?

**Comment by nicholasturner1** [comment]
Nice for the short-term, but not required. It will likely be required for proofreading phase 2.

**Comment by nkemnitz** [comment]
Think that's now part of the Annotation Framework - not Neuroglancer.
