### ISSUE TITLE
Integrate Ran's agglomeration into the pipeline

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#119]
We need this so everybody can run the pipeline.
And we also need code that can run at phase 2 scale.
Investigate using chunked watershed.

**Comment by tartavull** [comment]
Implement distributed mean affinity agglomeration
Claim low hanging fruit in agglomeration: contact area dependence and pre-mean non-linearities
Can we get away with single linkage mean affinity?
Need better understanding of Ran's thresholds and their interaction with watershed parameters

**Comment by nkemnitz** [comment]
Should be handled in [Igneous](https://github.com/seung-lab/igneous)
