### ISSUE TITLE
Correct right-click on synapse objects 

### ISSUE THREAD

**Issue by macrintr** [seung-lab/neuroglancer#12]
For synapse objects (pre & post coordinate pairs), right clicking on either pre or post point (in both the 2D & 3D) causes the viewport to change to the next synapse in the list. Make it so that right clicking on a synapse centers the viewport on that synapse.

**Comment by nkemnitz** [comment]
[fix(synapses): right-click jumps to correct synapse](https://github.com/seung-lab/neuroglancer/commit/7811a36f709d9979276fe0f1264a173ca38d2eed)
