### ISSUE TITLE
Include bounding cube in 3D

### ISSUE THREAD

**Issue by macrintr** [seung-lab/neuroglancer#122]
Make synapse bounding cube hack part of the UI in neuroglancer.

**Comment by nkemnitz** [comment]
@macrintr: Can you elaborate what that hack was / is this still an issue?

**Comment by macrintr** [comment]
This is a low priority. It's a useful hack for people using the state server.

**Comment by nkemnitz** [comment]
Note to myself: This is a feature request for displaying a cube / or other polygons in the 3D view. The mentioned hack uses one synapse for each edge of the cube.

**Comment by nkemnitz** [comment]
Added with 9c8a392391452b55b99ce597a7e5b94bef5620a3
