### ISSUE TITLE
Serialize to storage points and synapse layers

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#123]
If we have list of 100k point that won't fit in the url.
Is it reasonable to save that to gcs or s3  similarly an image layer?

**Comment by william-silversmith** [comment]
Might be a good case for indexDB + an export function. Otherwise the server
has to support user sessions.

**Comment by tartavull** [comment]
Maybe we can do something similar to skeletons or mesh serialization in precomputed

**Comment by nkemnitz** [comment]
Neuroglancer supports remotely stored annotations, I believe. Local annotations are stored in the JSON state, bypassing the URL limitation. And there is also the AnnotationFramework which is supposed to store annotations in a persistent way?
