### ISSUE TITLE
Ease install of packages in our workstations

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#128]
Write some documentation on how to install this package in our workstations
We should describe that you have to follow the Dockerfile to install the system libraries required

**Comment by tartavull** [comment]
We should specify that gcc>=5 is necessary to build the mesher, where gcc 4.8 is installed by default in our 14.04 workstations.
Here is a guide on how to install a newer gcc version 
https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

**Comment by macrintr** [comment]
Just to write it down, I was able to run `python setup.py develop` with gcc 6.3.0 after removing these lines: https://github.com/seung-lab/neuroglancer/blob/master/python/ext/src/on_demand_object_mesh_generator.cc#L32-L37

That recommendation came from @nicholasturner1.

Maybe want to separate Precomputed API from the mesher, too. Also probably want to mention how to get a `google-secret.json` & `aws-secret.json`. I just pulled them from another workstation.

**Comment by william-silversmith** [comment]
I figured out why you guys are having trouble with that line but I'm not. # __has_include is a C++17 feature that hasn't made it into gcc yet. On osx, gcc is by default an alias for clang, which includes support.

**Comment by william-silversmith** [comment]
https://clang.llvm.org/docs/LanguageExtensions.html

I should add this:
```
// To avoid problem with non-clang compilers not having this macro.
#if defined(__has_include)
#if __has_include("myinclude.h")
# include "myinclude.h"
#endif
#endif
```

**Comment by nkemnitz** [comment]
Python backend + Mesher is handled by [Igneous](https://github.com/seung-lab/igneous).
