### ISSUE TITLE
secret file path won't work without sudo 

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#142]
currently, the secret file was placed in `/secret`, which is not writable for normal users.
put them in home directory might be better, such as `~/.google_secret.json`?

**Comment by tartavull** [comment]
We currently inject the secrets for kubernets by mounting them as a temporary file system by mounting it at /secrets (the user is usually root so we could mount it there instead)
We also have the secrets in an encrypted file in travis, having it in /secrets . We want to make sure that they don't get released or shown in the travis build.

And the third place we use it is in our workstations were we have sudo.
but you're right, it's was an arbitrary, and we could change it.

**Comment by jingpengw** [comment]
sure, safety first. to make it work without sudo, we can add smarter reading of secret files or environment variables. this is not urgent.

**Comment by william-silversmith** [comment]
Maybe inside `~/.neuroglancer`?

**Comment by william-silversmith** [comment]
This is fixed in https://github.com/seung-lab/cloud-volume/

**Comment by william-silversmith** [comment]
We use ~/.cloudvolume now
