### ISSUE TITLE
Check for cosmic rays (GPU)

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#144]
We will have close to 200k cosmic rays in phase 2 hitting our GPU Ram which is not ECC
This computation assumes that we are using 6gb of RAM for 5 seconds to do a patch of 158x158x32
If a bit in the exponent gets hit it's likely that all the output affinities will close to 1.0 causing huge mergers.

Possible solutions:
1) build a shield around the dataservers
2) Rotate gpus on an angle that get less affected by cosmic rays.

**Comment by hsseung** [comment]
I believe K80 has ECC...that's generally true of server-grade GPUs but not the consumer-grade GPUs that we have in the lab.
