### ISSUE TITLE
license of zi is GPL 3.0

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#147]
the license of zi is GPL v3.0, which means that this package will be `infected` and becomes GPL licensed!

**Comment by tartavull** [comment]
Good catch! Another reason to get rid of it.
We currently have to mesher implementations, one for batch processing and another one for real time meshing.

**Comment by nkemnitz** [comment]
Mesher is now part of [Igneous](https://github.com/seung-lab/igneous)
