### ISSUE TITLE
[Feature Request] http2 access to AWS s3 through aws cloudfront

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#183]
aws cloudfront have http2 connection. since we are supposed to perform computation in AWS, it would be nice to keep the computation and storage at the same place.

**Comment by william-silversmith** [comment]
It's not entirely clear whether this would result in a major speedup. It well might, but the cloudfront servers are accessing the backend with http1. This would introduce an intermediate step, but then the cloudfront servers accelerate the final delivery.

**Comment by jingpengw** [comment]
not necessary for now since we are using gcloud.
