### ISSUE TITLE
[Feature Request] support blosc compression

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#186]
blosc has multiple threading support and have multiple compressor backends including zlib, zstd, blosclz, lz4, lz4hc, snappy.
My bigarray IO get 2-3X speedup using blosclz compression.

**Comment by nkemnitz** [comment]
Blosc might be a bit too heavy-weight for JavaScript. If you are talking about the affinities, let's first see how much improvement we get with the 24 Bit fixed point numbers?

**Comment by jingpengw** [comment]
since we have other similar options like zstd, and jp3d, close here.
