### ISSUE TITLE
Higher priority for ChunkedGraphChunks

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/neuroglancer#191]
Right now Neuroglancer will load chunks for images and segmentation layer first, starting at the coarsest MIP level; and only start the ChunkedGraphChunk requests once the finest resolution images are loaded. That takes several seconds even with good bandwidth and is super confusing to look at.

ChunkedGraphChunks should be loaded first(?). Or at least among the first chunks...

**Comment by sdorkenw** [comment]
I cannot stress enough how important this is. The current state makes proofreading (/ any use of the chunkedgraph interface) unusable for typical workflows when not having access to a 100 MB/s internet connection.

(1) It is unnecessary to download any low-res cubes if the user has zoomed to a small location. Something like an operating MIP which is automatically determined by the zoom level could be a good compromise. As an example: KNOSSOS (https://github.com/knossos-project/knossos) has implemented that.
(2) The same goes for the watershed layers. Segmentation cubes may be small but they still add HTTPS requests. 
(3) As stated by @nkemnitz, ChunkedGraph should be loaded first, or at least interleaved.
(4) The block size should be examined and potentially changed - 64^3 might be adding too many HTTPS requests. One should think about storing blocks of anisotropic size.
