### ISSUE TITLE
skeletons name is not consistent with mesh in info file

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#196]
in info JSON file, `skeletons` was named plural while `mesh` was named as singular. I would feel a little bit more comfortable if they were named consistently.
and `voxel_size` might be more accurate then the `resolution`.

**Comment by nkemnitz** [comment]
Think this is the same in google/neuroglancer. I understand the consistency issue, but I'd like to maintain compatibility with other NG forks.

**Comment by jingpengw** [comment]
ok, keep it as it is. close then.
