### ISSUE TITLE
Layer order is no longer preserved

### ISSUE THREAD

**Issue by bnehoran** [seung-lab/neuroglancer#228]
When sharing neuroglancer links, they open up with the layer order scrambled.

For example, in this link:
https://bit.ly/2yERnmF
If you place the `128` layer first, and duplicate the tab or share/copy the link, the layers reorder.

Chrome Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by sdorkenw** [comment]
@bnehoran: Do you mean when using the upload button to shorten the Link?

If so, we just fixed that in seung-lab/NeuroglancerJsonServer.

**Comment by bnehoran** [comment]
@sdorkenw No the upload button (if I understand what you're referring to, the "Post JSON to state server") doesn't actually work for me, so I haven't been using it.
What I'm referring to happens just from using the full Neuroglancer URL from the address bar of the browser (or alternatively, just refreshing the page).



[As an aside, and just to clarify, when I press the upload button, I get an error message "no state server found". If this is not supposed to happen, I can put this in a separate issue, but it seems to me that it is unrelated to this current issue.]

**Comment by nkemnitz** [comment]
Fixed by #240
