### ISSUE TITLE
Can't Access In From Home

### ISSUE THREAD

**Issue by BunPrinceton** [seung-lab/neuroglancer#241]
Hey I'm having trouble accessing neuroglancer from home. When I try to click on a save state of a shortened URL or the entire URL I get to a neuroglancer page called "Layout 4". When I hit the shorten button on this 'layout 4' I get an error: No state server found. I'm on windows 10.
![url_saves](https://user-images.githubusercontent.com/19410833/50360928-cb10fa00-052f-11e9-850f-ed7a0db362df.png)
![layout_4_edit](https://user-images.githubusercontent.com/19410833/50360974-001d4c80-0530-11e9-959a-028261961699.png)

![no_state_server](https://user-images.githubusercontent.com/19410833/50360857-7a999c80-052f-11e9-8826-1270f50dd038.png)

**Comment by sdorkenw** [comment]
Hi. To use the state server (shorten links) you have to be in the Princeton network (/ use the Princeton VPN).

**Comment by nkemnitz** [comment]
Closing this, as it currently works as intended - until we have a proper authentication/authorization system in place-
