### ISSUE TITLE
Too many segment ids cause neuroglancer to shift upwards hiding layers

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/neuroglancer#252]
I would like to share a link but I cannot access the shortner symbol. Just load a list of ids into the `pinky100 _sv16` dataset to replicate this. I have a list of example ids below.

Once adding many ids the neuroglancer window appears to shift upwards hiding the upper inch behind the browser bar and showing a black bar at the bottom. 

648518346341366885, 648518346341388820, 648518346341393609,
       648518346349470171, 648518346349471156, 648518346349471565,
       648518346349471910, 648518346349473044, 648518346349473160,
       648518346349473781, 648518346349473808, 648518346349473816,
       648518346349473819, 648518346349473832, 648518346349473844,
       648518346349473847, 648518346349473848, 648518346349474146,
       648518346349474703, 648518346349475035, 648518346349475150,
       648518346349475520, 648518346349475521, 648518346349475524,
       648518346349475530, 648518346349475531, 648518346349477981,
       648518346349478054, 648518346349478183, 648518346349478248,
       648518346349478348, 648518346349478380, 648518346349478431,
       648518346349478700, 648518346349478718, 648518346349478785,
       648518346349478913, 648518346349479056, 648518346349479094,
       648518346349479478, 648518346349479479, 648518346349479573,
       648518346349479981, 648518346349480499, 648518346349481014,
       648518346349482676, 648518346349483124, 648518346349483956,
       648518346349484607, 648518346349484832, 648518346349485870,
       648518346349486885, 648518346349490527, 648518346349490624,
       648518346349490749, 648518346349492097, 648518346349492662,
       648518346349493117, 648518346349494072, 648518346349494515,
       648518346349495481, 648518346349496103, 648518346349496245,
       648518346349496278, 648518346349497168, 648518346349497759,
       648518346349498835, 648518346349499005, 648518346349499085,
       648518346349499150, 648518346349499581, 648518346349499624,
       648518346349499636, 648518346349499679, 648518346349499680,
       648518346349499803, 648518346349499824, 648518346349499828,
       648518346349499851, 648518346349499852, 648518346349499876,
       648518346349499910, 648518346349499939, 648518346349500049,
       648518346349500126, 648518346349500138, 648518346349500163,
       648518346349500181, 648518346349500324, 648518346349500657,
       648518346349500725, 648518346349500939, 648518346349501175,
       648518346349501625, 648518346349501787, 648518346349503236,
       648518346349503591, 648518346349503592, 648518346349503767,
       648518346349503773, 648518346349504065, 648518346349504185,
       648518346349504442, 648518346349505911, 648518346349506092,
       648518346349506596, 648518346349506684, 648518346349506770,
       648518346349506803, 648518346349507355, 648518346349507717,
       648518346349507964

**Comment by nkemnitz** [comment]
@sdorkenw That only happens with Firefox? Haven't seen that behavior on Chrome...

**Comment by nkemnitz** [comment]
Confirmed that this was fixed in 4fede90648f8f2ddc25a16e47ce191bca4ff543a. I'll leave the issue open until we merged it.

**Comment by nkemnitz** [comment]
Fixed via #254
