### ISSUE TITLE
Inserting annotation causes whole AnnotationList to be rebuild

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/neuroglancer#253]
reported by @sdorkenw:
Programmatically adding many hundreds of annotations would slow down and sometimes even fail if there are many hundreds(?) of annotations in the list.

Likely cause is how the complete list gets rebuilt whenever a single annotation is added, deleted or otherwise modified.

**Comment by nkemnitz** [comment]
Resolved in #250. Have not created a PR for Google, yet.

**Comment by akhileshh** [comment]
created PR https://github.com/google/neuroglancer/pull/134
