### ISSUE TITLE
segment range 

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#266]
one segment id is not scalar, but have a range of segment ID!
How can it happen? I can show you the link and we can talk directly.

**Comment by manuel-castro** [comment]
Could you please post the link here?

**Comment by jingpengw** [comment]
@manuel-castro I would like to keep the link private for now since it was not published yet.

**Comment by jingpengw** [comment]
thanks for help @manuel-castro , it comes from segment equivalence specification.
