### ISSUE TITLE
Adding many segments or annotations obscures the view

### ISSUE THREAD

**Issue by nicholasturner1** [seung-lab/neuroglancer#269]
Recently I've noticed that viewing many segments or annotations will shift the view of the window out of sight. 

Here's a concrete example:
I start with a single segment and an empty annotation layer:
![neuroglancer - Google Chrome_999(001)](https://user-images.githubusercontent.com/1390187/58051421-20bdf280-7b20-11e9-89d2-bf29181a1527.png)
https://bit.ly/2HIoV6Z

Adding some points keeps the view consistent, but adding many points will make most of the screen black.
![neuroglancer - Google Chrome_999(002)](https://user-images.githubusercontent.com/1390187/58051450-33382c00-7b20-11e9-9c54-689b000f2fb5.png)
Each new point annotation shifts the view up and out of the frame more. Removing point annotations brings it back. I've noticed this on 2 Ubuntu machines using both Firefox and Chrome.

**Comment by manuel-castro** [comment]
Chrome 74 seems to have introduced this bug again

**Comment by manuel-castro** [comment]
I created an issue on google's branch. Maybe Jeremy can fix this again :D

https://github.com/google/neuroglancer/issues/137
