### ISSUE TITLE
the bounding box looks fragmented.

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/neuroglancer#274]
![image](https://user-images.githubusercontent.com/7651573/59387762-fc78be80-8d37-11e9-8c42-9a421ea999a1.png)

**Comment by nkemnitz** [comment]
Just an aliasing artifact, because the line width and feather are set to 1 pixel width. Could increase feather value... will make the line look slightly wider, though.

**Comment by nkemnitz** [comment]
Told bounding boxes and other lines to pull themselves together...
