### ISSUE TITLE
[graphene]: split preview

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/neuroglancer#285]
Many users requested a preview of a split decision before committing a multicut operation. We could provide a preview by exposing the mincut decision as an endpoint of the PyChunkedGraph. This would provide a local remapping according to the computed cut which could be displayed via remapping the supervoxels.

**Comment by nkemnitz** [comment]
Requires https://github.com/seung-lab/PyChunkedGraph/issues/148

**Comment by manuel-castro** [comment]
This functionality was merged in a while back
