### ISSUE TITLE
Test: test@basdf.com | gesw5y3wg

### ISSUE THREAD

**Issue by seung-issues** [seung-lab/neuroglancer#298]
| Email | Name | Type |
|---|---|---|
| test@basdf.com | Test | Bug and Suggestion |

Description: yuke56j4wh66h
![Imgur](https://i.imgur.com/9ajuFnw.png)
<details>
<summary>State URL</summary>

https://seun-report2githubissue-dot-neuromancer-seung-import.appspot.com/#!%7B%22layout%22:%224panel%22%7D
</details>

**Comment by manuel-castro** [comment]
This was me testing the PR. Closing.
