### ISSUE TITLE
fdsf:  | aswd

### ISSUE THREAD

**Issue by seung-issues** [seung-lab/neuroglancer#299]
| Email | Name | Type |
|---|---|---|
|  | fdsf |  |

Description: asdasd
![Imgur](https://i.imgur.com/qF3Z78C.jpg)
<details>
<summary>State URL</summary>

https://seun-report2githubissue-dot-neuromancer-seung-import.appspot.com/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://gs://neuroglancer/pinky100_v0/son_of_alignment_v15_rechunked%22%2C%22type%22:%22image%22%2C%22name%22:%22son_of_alignment_v15_rechunked%22%7D%2C%7B%22source%22:%22precomputed://gs://neuroglancer/pinky100_v0/seg/lost_no-random/bbox1_0%22%2C%22type%22:%22segmentation%22%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22name%22:%22bbox1_0%22%2C%22visible%22:false%7D%2C%7B%22source%22:%22graphene://https://www.dynamicannotationframework.com/segmentation/1.0/pinky100_sv16%22%2C%22type%22:%22segmentation_with_graph%22%2C%22segments%22:%5B%22648518346341388647%22%2C%22648518346341403356%22%2C%22648518346346708310%22%5D%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22chunkedGraph%22:%22https://www.dynamicannotationframework.com/segmentation/1.0/pinky100_sv16%22%2C%22graphOperationMarker%22:%5B%7B%22annotations%22:%5B%5D%2C%22tags%22:%5B%5D%7D%2C%7B%22annotations%22:%5B%5D%2C%22tags%22:%5B%5D%7D%5D%2C%22name%22:%22bbox1_01%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B4%2C4%2C40%5D%2C%22voxelCoordinates%22:%5B79967.9765625%2C57741.4921875%2C1089%5D%7D%7D%2C%22zoomFactor%22:11.545483957071834%7D%2C%22perspectiveZoom%22:153.69959261184266%2C%22showSlices%22:false%2C%22jsonStateServer%22:%22https://www.dynamicannotationframework.com/nglstate/post%22%2C%22selectedLayer%22:%7B%22layer%22:%22bbox1_01%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D
</details>

**Comment by manuel-castro** [comment]
This was me testing the PR. Closing.
