### ISSUE TITLE
Test One: test@1.com | 1 test

### ISSUE THREAD

**Issue by seung-issues** [seung-lab/neuroglancer#306]
| Email | Name | Type |
|---|---|---|
| test@1.com | Test One | Bug and Suggestion |

Description: fadfsAfdsafsagdfb
![Imgur](https://i.imgur.com/32hlcMP.png)
<details>
<summary>State URL</summary>

http://localhost:8080/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://gs://microns-seunglab/drosophila_v0/alignment/vector_fixer30_faster_v01/v4/image_stitch_v02%22%2C%22type%22:%22image%22%2C%22name%22:%22Image%22%7D%2C%7B%22source%22:%22graphene://https://fafbv2.dynamicannotationframework.com/segmentation/1.0/fly_v26%22%2C%22type%22:%22segmentation_with_graph%22%2C%22selectedAlpha%22:0.42%2C%22notSelectedAlpha%22:0.09%2C%22segments%22:%5B%22720575940629573089%22%5D%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22chunkedGraph%22:%22https://fafbv2.dynamicannotationframework.com/segmentation/1.0/fly_v26%22%2C%22graphOperationMarker%22:%5B%7B%22annotations%22:%5B%5D%2C%22tags%22:%5B%5D%7D%2C%7B%22annotations%22:%5B%5D%2C%22tags%22:%5B%5D%7D%5D%2C%22name%22:%22fly_playground%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B4%2C4%2C40%5D%2C%22voxelCoordinates%22:%5B163274.265625%2C75871.25%2C4741.4931640625%5D%7D%7D%2C%22zoomFactor%22:6.171101484112851%7D%2C%22perspectiveOrientation%22:%5B0.29237696528434753%2C-0.17863118648529053%2C0.04223601147532463%2C0.9385215640068054%5D%2C%22perspectiveZoom%22:4733.4020576910625%2C%22showSlices%22:false%2C%22gpuMemoryLimit%22:2000000000%2C%22jsonStateServer%22:%22https://www.dynamicannotationframework.com/nglstate/post%22%2C%22selectedLayer%22:%7B%22layer%22:%22fly_playground%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D
</details>

**Comment by ogewan** [comment]
working with fetch
