### ISSUE TITLE
neuroglancer deployment question

### ISSUE THREAD

**Issue by falkben** [seung-lab/neuroglancer#316]
Just a quick question about your NG deployment (https://neuromancer-seung-import.appspot.com/)

It looks like you haven't changed the default [showLayerDialog](https://github.com/seung-lab/neuroglancer/blob/master/src/neuroglancer/viewer.ts#L161-L164), however when I navigate to your deployment, it doesn't pop up the dialog.  Just wondering if that's in your build process, an environment variable, or an option somewhere else?

I'd like to enable the same behavior for [viz.neurodata.io](viz.neurodata.io), while keeping our codebase as close to google as possible.

Thanks!

**Comment by nkemnitz** [comment]
The deployment uses `npm run build-python-min` to provide the sockjs functionality that synchronizes the JSON state between Neuroglancer and potential Python user scripts. https://github.com/google/neuroglancer/blob/master/src/main_python.ts#L104 then overrides `showLayerDialog`.

**Comment by falkben** [comment]
Thanks!
