### ISSUE TITLE
Multicut annotation management tool is buggy with many points

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/neuroglancer#329]
When annotating many points for a multicut the widget on the lower right (after left key press) is not shown anymore for the annotations high in the list. It still shows up for those low on the list. 

Example: https://neuromancer-seung-import.appspot.com/?json_url=https://www.dynamicannotationframework.com/nglstate/4656646044909568

**Comment by nkemnitz** [comment]
Fixed in #343
