### ISSUE TITLE
Many annotations cause Neuroglancer to slow down

### ISSUE THREAD

**Issue by manuel-castro** [seung-lab/neuroglancer#364]
Too many DOM elements for annotations in the side panel cause Neuroglancer to lag considerably. After discussion, the developer team has come up with a solution: change the annotation list container such that only the annotations that are currently visible in the list exist on the DOM, the others having say `display: none`. Thus, the visible ones in the list are shown dynamically as you scroll up and down the list with the scrollbar.

**Comment by nkemnitz** [comment]
Maybe useful: https://github.com/NeXTs/Clusterize.js

**Comment by kaikue** [comment]
Clusterize.js removes non-visible elements from the DOM, which causes issues particularly with annotationListElements (which is used for various update operations under the assumption that every annotation element will exist in the DOM). I will investigate hiding annotation elements using display:none, so that elements are kept in the DOM but don't cause a slowdown from rendering.

**Comment by kaikue** [comment]
Profiling in Chrome suggests that this is due to forced reflow, caused by line 167 in display_context.ts. I opened an issue in the Google Neuroglancer repo to see if they have any insight: https://github.com/google/neuroglancer/issues/166

**Comment by jbms** [comment]
Doing a lazy list is a great idea, but it is quite tricky to implement, especially if the element height is not constant.  There are various existing libraries that attempt to achieve this, but they all have various tradeoffs and I'm not sure if any are particularly good.

I wrote one implementation here that does handle variable height: https://github.com/jbms/beancount-import/blob/master/frontend/virtual_list.tsx

However, it is react based (actually I think for this task react is just a hindrance) so it couldn't be used directly.
