### ISSUE TITLE
Integrate Jeremy's Fix for Annotation Elements

### ISSUE THREAD

**Issue by ogewan** [seung-lab/neuroglancer#366]
https://github.com/google/neuroglancer/pull/164/commits/a3e4c0d25dfad6d495e2f1a26972dfb41855b1a4

should be more like this, can be done while merging

https://github.com/google/neuroglancer/commit/a05650cd604887dd6ba8a23855a7afe99a89b7d0

https://github.com/seung-lab/neuroglancer/pull/360 will conflict if not merged first

**Comment by nkemnitz** [comment]
Done - see #372
