### ISSUE TITLE
Long URLs cause lag when moving 3D view

### ISSUE THREAD

**Issue by kaikue** [seung-lab/neuroglancer#370]
With a long URL (e.g. many annotations), Neuroglancer often becomes quite laggy when dragging the 3D view around. This is due to setUrlHash() being called repeatedly while dragging, when it should actually only happen once when the mouse is released. It seems that this behavior is triggered by clicking and dragging again immediately after releasing the previous drag.

**Comment by kaikue** [comment]
I believe the problem traces back to https://github.com/seung-lab/neuroglancer/blob/master/src/neuroglancer/ui/url_hash_binding.ts#L63

In particular, long URLs can cause setUrlHash() to take 100ms or more. Normally debounce prevents it from getting called multiple times in a row, but in this case I think the debounced setUrlHash function takes so much time that the debounce is able to again shortly afterwards, causing it to trigger repeatedly.

It looks like increasing updateDelayMilliseconds would fix this. It should probably be proportional to the length of the URL (since there's no need to wait 2 seconds for a short, near-instant URL). I'll try to figure out a good formula for this.

**Comment by kaikue** [comment]
Further investigation results: it's not as simple as increasing updateDelayMilliseconds. When the debounce function is created as part of the default view, it does not have access to the full state, so it doesn't know how long the URL will be. debounce does not let you change the wait time after you create it. I feel like there must be some sort of bug in debounce with slow functions, since it really shouldn't be getting called this frequently, but I haven't been able to pin it down. Tabling this for now since moving annotations into the state and out of the URL would make this a non-issue.

**Comment by ogewan** [comment]
This performance bug scales with annotation size quite fast. In addition, URL has a max size and max readable size. A simple fix can be to only save at discrete points: onBlur, onBeforeUnload (reload/quit), every 5 minutes or so and push to state server on save with a fallback to url in the state for now.

**Comment by nkemnitz** [comment]
Should be mitigated by #401

**Comment by kaikue** [comment]
Just tested, that does indeed seem to fix it.
