### ISSUE TITLE
Datasets Need Provenance Information

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/neuroglancer#38]
There should be a separate file, e.g. provenance.json that lists useful information about the dataset.

Here's an example:

```
{
    "dataset_name": "Zebrafish Cortex (something more exact)",
    "description":  "something about the experiment and anatomy",
    "collection_date": "2015-2016 or something more precise",
    "collected_by": Ashwin,
    
     -----
    "processing_method": convnet inference with JNet_v1,
    "processed_by": Jingpeng,
     … or … 
    "processing": [ 
        {  "method": convnet inference w/ JNet_v1, "executor": Jingpeng },
        {  "method": global watershed v2, "executor": Ran },
        {  "method": downsampling w/ countless algorithm, "executor": Will }
    ] 
    ----

    "uploaded_by": Jingpeng,
    "uploaded_date": today's date,
    "references": [ series of dois or urls ]
}
```

**Comment by tartavull** [comment]
I think this is something really necessary, and really useful.
I'm not sure if you want to do some processing from this files, but If it is just to store information entered by humans, using a wiki might be easier/more powerful.

**Comment by tartavull** [comment]
Even better might be to have some nice slack wiki integration
slack.com/apps/search?q=wiki

**Comment by william-silversmith** [comment]
That's a great idea. Maybe we store a wiki link in the info file? One
upside of having some key information in the info file is that it's all in
one place and we can run automated tests to ensure it's filled out.

On Mon, May 1, 2017 at 11:13 AM, Ignacio Tartavull <notifications@github.com

**Comment by william-silversmith** [comment]
Also, what does slack wiki integration do? I don't think I understand the concept.

**Comment by william-silversmith** [comment]
We have a PR #135 which includes a validation script. I think what Nacho meant by slack integration is that we can run a cron job with the validation script and notify people when a dataset is missing its provenance information.
