### ISSUE TITLE
shang: missing items in very short annotation list

### ISSUE THREAD

**Issue by seung-issues** [seung-lab/neuroglancer#386]
| Name | Type | OS | Browser |
|---|---|---|---|
| shang | Bug | Linux | Chrome |

Description: Annotation lists randomly missing a random number of items from the top. May or may not be related to multiple annotation layers, and all annotations (points) are visible in current view.
![Imgur](https://i.imgur.com/HikwMel.png)
<details>
<summary>State URL</summary>

https://neuromancer-seung-import.appspot.com/?json_url=https://www.dynamicannotationframework.com/nglstate/6753953538703360
</details>

**Comment by kaikue** [comment]
I haven't been able to replicate this, but it will probably be resolved once #377 gets merged in.

**Comment by shangmu** [comment]
To reproduce: switch between the different annotation layers. Pay attention to the top item and length (number of items) in the list - sometimes it's not obvious (also note the drastic difference in the number of visible dots and the number of shown items in the list in the provided screenshot). 

Presence of the segmentation layer is not necessary to reproduce the issue and can be deleted: https://neuromancer-seung-import.appspot.com/?json_url=https://www.dynamicannotationframework.com/nglstate/5355606676406272 (nkem's link)
