### ISSUE TITLE
Performance degrades with large annotation projects

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#395]
I'm working on a quick Neuroglancer-based task tagging 1000-2000 annotations. Using Chrome on Mac OS, performance is fine to begin with but degrades after tens of minutes and going through a few hundred annotations, sometimes bogging down my computer to the point of requiring a hard reset. This seems related to Chrome building a history of every URL change (30-40/minute) with URLs that are hundreds of thousands of characters long. This is not a particularly unusual task with connectomics data, so it will be extremely important to get this working smoothly going forward. I can imagine solutions of various forms: less frequent URL updating, automatic use of the JSON state server, or even a simple manual option to turn off URL updating that could be activated for specific use cases.

**Comment by ogewan** [comment]
There is an experimental feature implemented that deactivates all URL updating. The Autosave option in the User Preferences, accessed by pressing the '⚙' at the top right, disables this when unchecked. You have to manually re-enable it and it persists through reload. In addition, you have to make a state change (moving the view, new layer/annotation, etc.) to save after the option is re-enabled. Lastly, you can push to the state server with Autosave off and it correctly save. However, upon reload the url will reset.

In the future, Annotations will be moved out of the state and URL.
