### ISSUE TITLE
neuroglancer pollutes Chrome's browser history

### ISSUE THREAD

**Issue by shangmu** [seung-lab/neuroglancer#406]
Apparently state changes pollute the chrome's browser history with practically useless items (since they all have the same title, as seen in this screenshot).

Comparing to neuroglancer's lack of history in browser's Back/Forward buttons, what I personally prefer is the opposite: make state changes persistent in the Back/Forward tab history, and leave no redundant entries in browser history (although I have no idea if this is supported by Chrome's browser API and if Chrome API is the root cause of this issue).

@manuel-castro Is this (and/or the tab history route) perhaps also an alternative entry point for solving/implementing the recent "Undo" functionality? 

![image](https://user-images.githubusercontent.com/5497398/72946815-0d69c380-3d4e-11ea-9fa8-d7222ffbcde0.png)

**Comment by shangmu** [comment]
Haven's used browser history in years except today, and unfortunately this almost made it unusable for me.

**Comment by ogewan** [comment]
This should be resolved with #401 . Currently, Neuroglances pushes a history state for every state change. The new saving system uses replace state instead and back/forward is in between manually saved (remote) states.

IIRC Undo has nothing to do with history, the previous state is stored in memory at the time the undoable change is made.
