### ISSUE TITLE
bracket shortcuts show segmentation checkbox not in state

### ISSUE THREAD

**Issue by fcollman** [seung-lab/neuroglancer#425]
![image](https://user-images.githubusercontent.com/782341/77672335-0590f000-6f46-11ea-8f15-63337bec6dbc.png)
This checkbox is not part of the state, making it more complicated to explain how to use annotation tagging links than is required.  It would be nice if it were stored in the state.

**Comment by ceesem** [comment]
Note that this also applies to the "filter by segmentation" flag.

These options are an important factor in getting consistent behavior during the programmatic generation of neuroglancer states, which is a frequent part of workflows visualizing and correcting analysis and adding new annotations.

**Comment by manuel-castro** [comment]
Fixed in master as of fb1c6ff

**Comment by fcollman** [comment]
Thank you!!!
