### ISSUE TITLE
Things to Consider

### ISSUE THREAD

**Issue by BunPrinceton** [seung-lab/neuroglancer#442]
- some type of recent bin for segment IDs of recently selected (if you lose a segment in the fray of working you can check the list of recent segments)

- a merge setting that only lets merges with selected segments, to avoid misclicks (in 2D)

- a tool for storing merges and executing them all at once
![Merge_Store](https://user-images.githubusercontent.com/19410833/80131022-966be300-8567-11ea-9ad0-e666b35f59b6.png)

**Comment by manuel-castro** [comment]
Hey thank you for the suggestions! A GitHub issue is only meant to be for a single request however. I'm going to close this issue but it'd be great if you could make three new issues. Sorry to put you through this inconvenience.
