### ISSUE TITLE
Fail gracefully on non-WebGL2 browsers (i.e. iOS or Safari)

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#443]
Projects are starting to use Neuroglancer to show data to a very broad audience. While we can explain the browser compatibility as clearly as possible, at the end of the day people are not all going to read carefully before clicking links (e.g. if they see a link on twitter). It would be great to not discourage interested people coming in with iOS or Safari if Neuroglancer had an informative error page that let them know how to access the link.

**Comment by ceesem** [comment]
This remains easy and extremely important for data sharing.

**Comment by manuel-castro** [comment]
Fixed in master as of 93d9089

**Comment by ceesem** [comment]
Thank you!
