### ISSUE TITLE
automatically load segmentation when pressing bracket button not in state

### ISSUE THREAD

**Issue by fcollman** [seung-lab/neuroglancer#448]
The checkbox you press so that segmentation IDs automatically load when you press the [ or ] keys, is not part of the state.  This means when you send someone a link that is designed for them to click through annotations to reveal locations in the dataset, they have to know to click this small box in a menu.  For experienced users this is fine, but I have had to explain this to every new user I interact with and the box is small and unintuitive.  If it were part of the state I could send them a link that would have it pre-checked.  Alternatively, can it be checked by default, rather than unchecked by default?

**Comment by fcollman** [comment]
![image](https://user-images.githubusercontent.com/782341/80871379-19282880-8c61-11ea-85a3-a87c3d5438c7.png)
This is the button i'm speaking of... "bracket shortcuts show segmentation"

**Comment by manuel-castro** [comment]
Fixed in master as of fb1c6ff
