### ISSUE TITLE
Layer bar items changing size disrupts display and can cause unstable view

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#450]
When layer boxes change size and wrap to a new line below, this moves the image display underneath. This is a problem when the layer boxes are changing size due to displaying the root id under the cursor (or in the case of graphene segmentations, both the supervoxel and the root id), because the screen jumps up and down constantly while browsing. It is particularly bad when the jump moves the display in such a way that the cursor is initially under a segmentation, then jumps to empty space, causing the box to shrink and the display to jump back. This will just jump back and forth until the cursor is moved, and makes it almost impossible to select such a spot. Keeping the image view steady no matter what is underneath the cursor would be good.

**Comment by ceesem** [comment]
With recent success in proofreading on large volumes, this problem has become extremely clear again and remains a friction point.

**Comment by manuel-castro** [comment]
The layer item now no longer shrinks, which should fix the problem.
