### ISSUE TITLE
Null segmentations are mishandled during split mode

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#468]
When one goes into split mode on a graphene chunked graph layer, the screen should darken around all but the selected segmentation. However, when there are places where the supervoxel layer has id 0 segmentation values (as in the case with Minnie, where myelin is unsegmented), a couple of issues seem to arise.

1) Voxels with id 0 are not darkened.
2) It seems like the id 0 values are capturing point lookups when split points are added from the mesh view (and thus a supervoxel needs to be determined. I suspect this because when such points are near myelin, I sometimes get the error "Split failed: Cannot find root id 0".

An example of such a state: https://akhilesh-graphene-sharded-dot-neuromancer-seung-import.appspot.com/?json_url=https://globalv1.daf-apis.com/nglstate/api/v1/5984143825436672

**Comment by manuel-castro** [comment]
This is now fixed (you can view your link to see)
