### ISSUE TITLE
Annotations with nulls produce an unreadable state

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#473]
It is possible for the user to create annotations with null values (ellipsoids, for example, give NaN for the radius values if you double click too fast). If a user saves a state like this where an annotation has null values and Neuroglancer refuses to render the layer. This is frustrating for the user, since that seems like it destroys the data they produced and it's difficult to recover without someone who knows how to go in and fix the raw JSON state directly.

Here's an example where the radii field was set to None for one ellipsoid: https://akhilesh-graphene-sharded-dot-neuromancer-seung-import.appspot.com/?json_url=https://globalv1.daf-apis.com/nglstate/api/v1/5163217827397632

**Comment by ogewan** [comment]
This is resolved in #413 but hasn't been merged yet :anguished:

**Comment by akhileshh** [comment]
rebased on master, should be fixed on `graphene-sharded` branch as well
