### ISSUE TITLE
Unselecting an object is too easy, inconsistent and destructive

### ISSUE THREAD

**Issue by ceesem** [seung-lab/neuroglancer#493]
It is extremely easy to deselect objects and extremely hard to re-select them. Now that neuroglancer is in a proofreading workflow, we are often doing a lot of work focused around a single neuron. Common tasks include selecting a continuation of some branch and removing erroneous merges before merging it into the main neuron. In effect, you have one or several objects that you need to keep selected to keep working and basically no way of finding them other than clicking specific spots in the segmentation. Unfortunately, an accidental double click in the 3d imagery (this seems to occur a lot to me while I'm rotating the scene on my trackpad) or a misplaced single click in the id list will unselect a neuron and there is virtually no way to recover that selection unless there is still some sort of spatial landmark that happens to be available. On occasion, I've just given up on looking into an interesting neuron that I ran across because I couldn't find it again after such a deselection.

I know it would be a big interface change, but I would suggest making deselection a much more standardized, ideally currently unused or under-used modifier (I'd say shift-click, as the rotation feature is used much, much less often than selecting/deselecting objects even if we had isotropic data). I'd further suggest that this modifier would apply across all ways of deselecting or deleting objects. That is, whatever modifier-click deselects objects in the data views deselects is the same way of deselecting them from an ID list.

**Comment by ogewan** [comment]
There is a project to add global undo/redo to NG that seems like it will address this

**Comment by ceesem** [comment]
Agreed, that branch looks like it would address this issue well.

**Comment by ceesem** [comment]
I think this is resolved by the undo feature, thank you!
