### ISSUE TITLE
Adjust save-state-getjson behavior to return save-state if no state server is found

### ISSUE THREAD

**Issue by macrintr** [seung-lab/neuroglancer#552]
I frequently use the `save-state-getjson` shortcut to copy and paste a link, only to find that there's no link in my buffer because there was no state server for my session. The alert in the message bar at the bottom of the screen is too subtle to catch my attention, and it leaves me with a few steps to add a state server url. 

I think a better behavior might be to have `save-state-getjson` default to `save-state` if there is no state server present. That would clearly indicate to the user that no link was copied, and it would put the user one step closer to entering a state server url so they can get on with the copying.

**Comment by manuel-castro** [comment]
Fixed by 39d9f18
