### ISSUE TITLE
Improve travisci speed by caching docker

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#59]
https://github.com/travis-ci/travis-ci/issues/5358

**Comment by william-silversmith** [comment]
I wonder if it might be possible to use non-ephemeral VMs for "fast" builds, though that would take us firmly out of Travis territory.

**Comment by tartavull** [comment]
This seems to be important, docker building is taking unnecessary long time

**Comment by nkemnitz** [comment]
Fast, since we only deal with frontend Neuroglancer in Travis now.
