### ISSUE TITLE
Use dataset instead of textContent

### ISSUE THREAD

**Issue by ChrisRaven** [seung-lab/neuroglancer#600]
In file https://github.com/seung-lab/neuroglancer/blob/master/src/neuroglancer/widget/segment_set_widget.ts in line 380 (function setItemButtonColor() ), there's:
```const segmentIDString = itemButton.textContent!;```

Could you use this instead?
```const segmentIDString = itemButton.dataset.segId;```

Currently it collides with my Names plugin.
Also, reading the data from the already existing dataset would look a little bit better, than reading from the UI.

Edit: Same in the createItemButton() method (line 249). It's there 3 times - one in each event listener.

**Comment by ChrisRaven** [comment]
Same in the createItemButton() method (line 249). It's there 3 times - one in each event listener.

**Comment by chrisj** [comment]
Hi Krzysztof,

That seems like a good change to me, I'll make the change.  I thinkrename ability should be built in to neuroglancer, I'd like to propose it to Jeremy, the creator of neuroglancer. At some point we will be swapping ng-extend to be based on the google branch, or a fork that closely follows that branch.

**Comment by ChrisRaven** [comment]
Hi Chris,

Thank you!
And I agree, that it should be a built in ability. It's a simple thing, but improves things greatly, when working with many cells (speaking from experience).

Cheers,
KK



----- Original Message -----
From: Chris Jordan ***@***.***>
To: seung-lab/neuroglancer ***@***.***>
Cc: Krzysztof Kruk ***@***.***>,  Author ***@***.***>
Date: Fri, 09 Sep 2022 09:25:01 -0700
Subject: Re: [seung-lab/neuroglancer] Use dataset instead of textContent (Issue #600)

**Comment by ChrisRaven** [comment]
Hi Chris,

Thank you! Speaking from experience, naming cells should definitely be a built in feature. It helps greatly, when working with many cells.
