### ISSUE TITLE
Multi threading read support for precomputed

### ISSUE THREAD

**Issue by tartavull** [seung-lab/neuroglancer#94]
Precomputed can currently concurrently write data to storage but not reading
time estimate: <1d

**Comment by tartavull** [comment]
This will improve efficiency of the pipeline by making reading volumes faster

**Comment by william-silversmith** [comment]
This is done already: 

https://github.com/seung-lab/neuroglancer/blob/quantizedaffinities/python/neuroglancer/pipeline/volumes/cloudvolume.py
